const dummyData = {
    location: {
        name: "Haryana",
        region: "India",
        country: "India",
        lat: 42.85,
        lon: -80.5,
        tz_id: "America/Toronto",
        localtime_epoch: 1707559109,
        localtime: "2024-02-10 4:58"
    },
    current: {
        last_updated_epoch: 1707558300,
        last_updated: "2024-02-10 04:45",
        temp_c: 7.5,
        temp_f: 45.5,
        is_day: 0,
        condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000
        },
        wind_mph: 5.6,
        wind_kph: 9,
        wind_degree: 230,
        wind_dir: "SW",
        pressure_mb: 1009,
        pressure_in: 29.79,
        precip_mm: 0.22,
        precip_in: 0.01,
        humidity: 89,
        cloud: 0,
        feelslike_c: 4.1,
        feelslike_f: 39.4,
        vis_km: 10,
        vis_miles: 6,
        uv: 1,
        gust_mph: 23.8,
        gust_kph: 38.3
    },
    forecast: {
        forecastday: [
            {
                date: "2024-02-10",
                date_epoch: 1707523200,
                day: {
                    maxtemp_c: 8.2,
                    maxtemp_f: 46.7,
                    mintemp_c: 2.4,
                    mintemp_f: 36.3,
                    avgtemp_c: 6,
                    avgtemp_f: 42.7,
                    maxwind_mph: 17,
                    maxwind_kph: 27.4,
                    totalprecip_mm: 3.38,
                    totalprecip_in: 0.13,
                    totalsnow_cm: 0,
                    avgvis_km: 9.9,
                    avgvis_miles: 6,
                    avghumidity: 80,
                    daily_will_it_rain: 1,
                    daily_chance_of_rain: 94,
                    daily_will_it_snow: 0,
                    daily_chance_of_snow: 0,
                    condition: {
                        text: "Patchy rain nearby",
                        icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        code: 1063
                    },
                    uv: 2
                },
                astro: {
                    sunrise: "07:27 AM",
                    sunset: "05:47 PM",
                    moonrise: "08:12 AM",
                    moonset: "06:50 PM",
                    moon_phase: "Waxing Crescent",
                    moon_illumination: 0,
                    is_moon_up: 0,
                    is_sun_up: 0
                },
                hour: [
                    {
                        time_epoch: 1707541200,
                        time: "2024-02-10 00:00",
                        temp_c: 6.8,
                        temp_f: 44.3,
                        is_day: 0,
                        condition: {
                            text: "Patchy rain nearby",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            code: 1063
                        },
                        wind_mph: 14.3,
                        wind_kph: 23,
                        wind_degree: 235,
                        wind_dir: "SW",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0.59,
                        precip_in: 0.02,
                        snow_cm: 0,
                        humidity: 93,
                        cloud: 88,
                        feelslike_c: 3,
                        feelslike_f: 37.4,
                        windchill_c: 3,
                        windchill_f: 37.4,
                        heatindex_c: 6.8,
                        heatindex_f: 44.3,
                        dewpoint_c: 5.8,
                        dewpoint_f: 42.4,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 9,
                        vis_miles: 5,
                        gust_mph: 28.6,
                        gust_kph: 46,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707544800,
                        time: "2024-02-10 01:00",
                        temp_c: 6.6,
                        temp_f: 43.9,
                        is_day: 0,
                        condition: {
                            text: "Patchy rain nearby",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            code: 1063
                        },
                        wind_mph: 14.3,
                        wind_kph: 23,
                        wind_degree: 236,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0.6,
                        precip_in: 0.02,
                        snow_cm: 0,
                        humidity: 94,
                        cloud: 79,
                        feelslike_c: 2.7,
                        feelslike_f: 36.8,
                        windchill_c: 2.7,
                        windchill_f: 36.8,
                        heatindex_c: 6.6,
                        heatindex_f: 43.9,
                        dewpoint_c: 5.6,
                        dewpoint_f: 42,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 9,
                        vis_miles: 5,
                        gust_mph: 28.8,
                        gust_kph: 46.3,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707548400,
                        time: "2024-02-10 02:00",
                        temp_c: 6.5,
                        temp_f: 43.7,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240
                        },
                        wind_mph: 15.2,
                        wind_kph: 24.5,
                        wind_degree: 243,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.79,
                        precip_mm: 0.93,
                        precip_in: 0.04,
                        snow_cm: 0,
                        humidity: 97,
                        cloud: 100,
                        feelslike_c: 2.5,
                        feelslike_f: 36.6,
                        windchill_c: 2.5,
                        windchill_f: 36.6,
                        heatindex_c: 6.5,
                        heatindex_f: 43.7,
                        dewpoint_c: 5.9,
                        dewpoint_f: 42.6,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 27.9,
                        gust_kph: 44.9,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707552000,
                        time: "2024-02-10 03:00",
                        temp_c: 6.3,
                        temp_f: 43.3,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240
                        },
                        wind_mph: 14.8,
                        wind_kph: 23.8,
                        wind_degree: 244,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0.39,
                        precip_in: 0.02,
                        snow_cm: 0,
                        humidity: 97,
                        cloud: 100,
                        feelslike_c: 2.5,
                        feelslike_f: 36.4,
                        windchill_c: 2.5,
                        windchill_f: 36.4,
                        heatindex_c: 6.3,
                        heatindex_f: 43.3,
                        dewpoint_c: 6,
                        dewpoint_f: 42.7,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 26.2,
                        gust_kph: 42.2,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707555600,
                        time: "2024-02-10 04:00",
                        temp_c: 7.5,
                        temp_f: 45.5,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000
                        },
                        wind_mph: 5.6,
                        wind_kph: 9,
                        wind_degree: 230,
                        wind_dir: "SW",
                        pressure_mb: 1009,
                        pressure_in: 29.79,
                        precip_mm: 0.22,
                        precip_in: 0.01,
                        snow_cm: 0,
                        humidity: 89,
                        cloud: 0,
                        feelslike_c: 2.4,
                        feelslike_f: 36.4,
                        windchill_c: 2.4,
                        windchill_f: 36.4,
                        heatindex_c: 6.1,
                        heatindex_f: 43,
                        dewpoint_c: 5.8,
                        dewpoint_f: 42.5,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 23.8,
                        gust_kph: 38.3,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707559200,
                        time: "2024-02-10 05:00",
                        temp_c: 5.9,
                        temp_f: 42.7,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240
                        },
                        wind_mph: 11.6,
                        wind_kph: 18.7,
                        wind_degree: 239,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.79,
                        precip_mm: 0.23,
                        precip_in: 0.01,
                        snow_cm: 0,
                        humidity: 99,
                        cloud: 100,
                        feelslike_c: 2.5,
                        feelslike_f: 36.4,
                        windchill_c: 2.5,
                        windchill_f: 36.4,
                        heatindex_c: 5.9,
                        heatindex_f: 42.6,
                        dewpoint_c: 5.8,
                        dewpoint_f: 42.4,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 21.7,
                        gust_kph: 34.8,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707562800,
                        time: "2024-02-10 06:00",
                        temp_c: 5.7,
                        temp_f: 42.3,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240
                        },
                        wind_mph: 9.8,
                        wind_kph: 15.8,
                        wind_degree: 246,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.79,
                        precip_mm: 0.27,
                        precip_in: 0.01,
                        snow_cm: 0,
                        humidity: 99,
                        cloud: 95,
                        feelslike_c: 2.5,
                        feelslike_f: 36.4,
                        windchill_c: 2.5,
                        windchill_f: 36.4,
                        heatindex_c: 5.7,
                        heatindex_f: 42.3,
                        dewpoint_c: 5.5,
                        dewpoint_f: 41.9,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 18.6,
                        gust_kph: 30,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707566400,
                        time: "2024-02-10 07:00",
                        temp_c: 5.6,
                        temp_f: 42,
                        is_day: 0,
                        condition: {
                            text: "Patchy rain nearby",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            code: 1063
                        },
                        wind_mph: 9.2,
                        wind_kph: 14.8,
                        wind_degree: 237,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0.12,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 99,
                        cloud: 100,
                        feelslike_c: 2.4,
                        feelslike_f: 36.4,
                        windchill_c: 2.4,
                        windchill_f: 36.4,
                        heatindex_c: 5.6,
                        heatindex_f: 42,
                        dewpoint_c: 5.4,
                        dewpoint_f: 41.6,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 18.5,
                        gust_kph: 29.8,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707570000,
                        time: "2024-02-10 08:00",
                        temp_c: 5.5,
                        temp_f: 41.9,
                        is_day: 1,
                        condition: {
                            text: "Patchy rain nearby",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            code: 1063
                        },
                        wind_mph: 8.7,
                        wind_kph: 14,
                        wind_degree: 235,
                        wind_dir: "SW",
                        pressure_mb: 1009,
                        pressure_in: 29.79,
                        precip_mm: 0.01,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 99,
                        cloud: 99,
                        feelslike_c: 2.5,
                        feelslike_f: 36.4,
                        windchill_c: 2.5,
                        windchill_f: 36.4,
                        heatindex_c: 5.5,
                        heatindex_f: 41.9,
                        dewpoint_c: 5.2,
                        dewpoint_f: 41.4,
                        will_it_rain: 1,
                        chance_of_rain: 76,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 17.8,
                        gust_kph: 28.7,
                        uv: 2,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707573600,
                        time: "2024-02-10 09:00",
                        temp_c: 5.7,
                        temp_f: 42.3,
                        is_day: 1,
                        condition: {
                            text: "Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            code: 1006
                        },
                        wind_mph: 8.5,
                        wind_kph: 13.7,
                        wind_degree: 245,
                        wind_dir: "WSW",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 98,
                        cloud: 86,
                        feelslike_c: 2.5,
                        feelslike_f: 36.6,
                        windchill_c: 2.5,
                        windchill_f: 36.6,
                        heatindex_c: 5.7,
                        heatindex_f: 42.3,
                        dewpoint_c: 5.2,
                        dewpoint_f: 41.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 17.3,
                        gust_kph: 27.8,
                        uv: 2,
                        short_rad: 4.94,
                        diff_rad: 2.61
                    },
                    {
                        time_epoch: 1707577200,
                        time: "2024-02-10 10:00",
                        temp_c: 6.3,
                        temp_f: 43.3,
                        is_day: 1,
                        condition: {
                            text: "Partly Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003
                        },
                        wind_mph: 10.7,
                        wind_kph: 17.3,
                        wind_degree: 251,
                        wind_dir: "WSW",
                        pressure_mb: 1010,
                        pressure_in: 29.82,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 93,
                        cloud: 53,
                        feelslike_c: 2.9,
                        feelslike_f: 37.1,
                        windchill_c: 2.9,
                        windchill_f: 37.1,
                        heatindex_c: 6.3,
                        heatindex_f: 43.3,
                        dewpoint_c: 4.9,
                        dewpoint_f: 40.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 20.3,
                        gust_kph: 32.7,
                        uv: 3,
                        short_rad: 38.14,
                        diff_rad: 19.06
                    },
                    {
                        time_epoch: 1707580800,
                        time: "2024-02-10 11:00",
                        temp_c: 6.9,
                        temp_f: 44.4,
                        is_day: 1,
                        condition: {
                            text: "Partly Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003
                        },
                        wind_mph: 13.4,
                        wind_kph: 21.6,
                        wind_degree: 261,
                        wind_dir: "W",
                        pressure_mb: 1010,
                        pressure_in: 29.82,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 80,
                        cloud: 38,
                        feelslike_c: 3.3,
                        feelslike_f: 38,
                        windchill_c: 3.3,
                        windchill_f: 38,
                        heatindex_c: 6.9,
                        heatindex_f: 44.4,
                        dewpoint_c: 3.7,
                        dewpoint_f: 38.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 22.4,
                        gust_kph: 36,
                        uv: 3,
                        short_rad: 108.54,
                        diff_rad: 42.22
                    },
                    {
                        time_epoch: 1707584400,
                        time: "2024-02-10 12:00",
                        temp_c: 7.4,
                        temp_f: 45.3,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000
                        },
                        wind_mph: 14.8,
                        wind_kph: 23.8,
                        wind_degree: 263,
                        wind_dir: "W",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 68,
                        cloud: 16,
                        feelslike_c: 3.7,
                        feelslike_f: 38.7,
                        windchill_c: 3.7,
                        windchill_f: 38.7,
                        heatindex_c: 7.4,
                        heatindex_f: 45.3,
                        dewpoint_c: 2,
                        dewpoint_f: 35.5,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 22.8,
                        gust_kph: 36.7,
                        uv: 3,
                        short_rad: 183.2,
                        diff_rad: 55.78
                    },
                    {
                        time_epoch: 1707588000,
                        time: "2024-02-10 13:00",
                        temp_c: 7.7,
                        temp_f: 45.9,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000
                        },
                        wind_mph: 15.9,
                        wind_kph: 25.6,
                        wind_degree: 260,
                        wind_dir: "W",
                        pressure_mb: 1010,
                        pressure_in: 29.82,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 63,
                        cloud: 6,
                        feelslike_c: 4.1,
                        feelslike_f: 39.3,
                        windchill_c: 4.1,
                        windchill_f: 39.3,
                        heatindex_c: 7.7,
                        heatindex_f: 45.9,
                        dewpoint_c: 1.4,
                        dewpoint_f: 34.5,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 23.4,
                        gust_kph: 37.7,
                        uv: 3,
                        short_rad: 246.74,
                        diff_rad: 64.51
                    },
                    {
                        time_epoch: 1707591600,
                        time: "2024-02-10 14:00",
                        temp_c: 8,
                        temp_f: 46.3,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000
                        },
                        wind_mph: 16.3,
                        wind_kph: 26.3,
                        wind_degree: 261,
                        wind_dir: "W",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 61,
                        cloud: 6,
                        feelslike_c: 4.2,
                        feelslike_f: 39.6,
                        windchill_c: 4.2,
                        windchill_f: 39.6,
                        heatindex_c: 8,
                        heatindex_f: 46.3,
                        dewpoint_c: 1,
                        dewpoint_f: 33.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 23.5,
                        gust_kph: 37.9,
                        uv: 3,
                        short_rad: 295.9,
                        diff_rad: 69.5
                    },
                    {
                        time_epoch: 1707595200,
                        time: "2024-02-10 15:00",
                        temp_c: 7.9,
                        temp_f: 46.2,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000
                        },
                        wind_mph: 17,
                        wind_kph: 27.4,
                        wind_degree: 261,
                        wind_dir: "W",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 59,
                        cloud: 7,
                        feelslike_c: 4.1,
                        feelslike_f: 39.4,
                        windchill_c: 4.1,
                        windchill_f: 39.4,
                        heatindex_c: 7.9,
                        heatindex_f: 46.2,
                        dewpoint_c: 0.6,
                        dewpoint_f: 33,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 24.3,
                        gust_kph: 39.2,
                        uv: 3,
                        short_rad: 482.96,
                        diff_rad: 152.11
                    },
                    {
                        time_epoch: 1707598800,
                        time: "2024-02-10 16:00",
                        temp_c: 7.5,
                        temp_f: 45.5,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000
                        },
                        wind_mph: 16.8,
                        wind_kph: 27,
                        wind_degree: 271,
                        wind_dir: "W",
                        pressure_mb: 1009,
                        pressure_in: 29.8,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 59,
                        cloud: 4,
                        feelslike_c: 3.7,
                        feelslike_f: 38.6,
                        windchill_c: 3.7,
                        windchill_f: 38.6,
                        heatindex_c: 7.5,
                        heatindex_f: 45.5,
                        dewpoint_c: 0.2,
                        dewpoint_f: 32.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 24.4,
                        gust_kph: 39.2,
                        uv: 3,
                        short_rad: 464.04,
                        diff_rad: 116.91
                    },
                    {
                        time_epoch: 1707602400,
                        time: "2024-02-10 17:00",
                        temp_c: 6.7,
                        temp_f: 44,
                        is_day: 1,
                        condition: {
                            text: "Partly Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003
                        },
                        wind_mph: 15,
                        wind_kph: 24.1,
                        wind_degree: 274,
                        wind_dir: "W",
                        pressure_mb: 1010,
                        pressure_in: 29.82,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 61,
                        cloud: 32,
                        feelslike_c: 2.8,
                        feelslike_f: 37,
                        windchill_c: 2.8,
                        windchill_f: 37,
                        heatindex_c: 6.7,
                        heatindex_f: 44,
                        dewpoint_c: 0.1,
                        dewpoint_f: 32.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 22.2,
                        gust_kph: 35.7,
                        uv: 3,
                        short_rad: 404.14,
                        diff_rad: 113.59
                    },
                    {
                        time_epoch: 1707606000,
                        time: "2024-02-10 18:00",
                        temp_c: 5.7,
                        temp_f: 42.2,
                        is_day: 0,
                        condition: {
                            text: "Overcast ",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            code: 1009
                        },
                        wind_mph: 14.1,
                        wind_kph: 22.7,
                        wind_degree: 282,
                        wind_dir: "WNW",
                        pressure_mb: 1010,
                        pressure_in: 29.84,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 64,
                        cloud: 100,
                        feelslike_c: 1.8,
                        feelslike_f: 35.2,
                        windchill_c: 1.8,
                        windchill_f: 35.2,
                        heatindex_c: 5.7,
                        heatindex_f: 42.2,
                        dewpoint_c: -0.5,
                        dewpoint_f: 31.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 22,
                        gust_kph: 35.4,
                        uv: 1,
                        short_rad: 332.42,
                        diff_rad: 99.07
                    },
                    {
                        time_epoch: 1707609600,
                        time: "2024-02-10 19:00",
                        temp_c: 4.9,
                        temp_f: 40.9,
                        is_day: 0,
                        condition: {
                            text: "Partly Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003
                        },
                        wind_mph: 12.1,
                        wind_kph: 19.4,
                        wind_degree: 287,
                        wind_dir: "WNW",
                        pressure_mb: 1011,
                        pressure_in: 29.86,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 66,
                        cloud: 41,
                        feelslike_c: 1,
                        feelslike_f: 33.8,
                        windchill_c: 1,
                        windchill_f: 33.8,
                        heatindex_c: 4.9,
                        heatindex_f: 40.9,
                        dewpoint_c: -1.1,
                        dewpoint_f: 30,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 19.5,
                        gust_kph: 31.4,
                        uv: 1,
                        short_rad: 270.02,
                        diff_rad: 81.1
                    },
                    {
                        time_epoch: 1707613200,
                        time: "2024-02-10 20:00",
                        temp_c: 4.2,
                        temp_f: 39.5,
                        is_day: 0,
                        condition: {
                            text: "Partly Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003
                        },
                        wind_mph: 11.4,
                        wind_kph: 18.4,
                        wind_degree: 291,
                        wind_dir: "WNW",
                        pressure_mb: 1013,
                        pressure_in: 29.9,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 67,
                        cloud: 30,
                        feelslike_c: 0.3,
                        feelslike_f: 32.6,
                        windchill_c: 0.3,
                        windchill_f: 32.6,
                        heatindex_c: 4.2,
                        heatindex_f: 39.5,
                        dewpoint_c: -1.4,
                        dewpoint_f: 29.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 18.2,
                        gust_kph: 29.3,
                        uv: 1,
                        short_rad: 225.02,
                        diff_rad: 67.58
                    },
                    {
                        time_epoch: 1707616800,
                        time: "2024-02-10 21:00",
                        temp_c: 3.5,
                        temp_f: 38.3,
                        is_day: 0,
                        condition: {
                            text: "Clear ",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000
                        },
                        wind_mph: 9.8,
                        wind_kph: 15.8,
                        wind_degree: 304,
                        wind_dir: "NW",
                        pressure_mb: 1013,
                        pressure_in: 29.92,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 69,
                        cloud: 20,
                        feelslike_c: -0.2,
                        feelslike_f: 31.7,
                        windchill_c: -0.2,
                        windchill_f: 31.7,
                        heatindex_c: 3.5,
                        heatindex_f: 38.3,
                        dewpoint_c: -1.7,
                        dewpoint_f: 28.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 15.5,
                        gust_kph: 25,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707620400,
                        time: "2024-02-10 22:00",
                        temp_c: 2.9,
                        temp_f: 37.3,
                        is_day: 0,
                        condition: {
                            text: "Clear ",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000
                        },
                        wind_mph: 8.3,
                        wind_kph: 13.3,
                        wind_degree: 300,
                        wind_dir: "WNW",
                        pressure_mb: 1014,
                        pressure_in: 29.95,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 71,
                        cloud: 8,
                        feelslike_c: -0.6,
                        feelslike_f: 30.9,
                        windchill_c: -0.6,
                        windchill_f: 30.9,
                        heatindex_c: 2.9,
                        heatindex_f: 37.3,
                        dewpoint_c: -2,
                        dewpoint_f: 28.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 12.9,
                        gust_kph: 20.7,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    },
                    {
                        time_epoch: 1707624000,
                        time: "2024-02-10 23:00",
                        temp_c: 2.5,
                        temp_f: 36.4,
                        is_day: 0,
                        condition: {
                            text: "Partly Cloudy ",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003
                        },
                        wind_mph: 8.1,
                        wind_kph: 13,
                        wind_degree: 307,
                        wind_dir: "NW",
                        pressure_mb: 1015,
                        pressure_in: 29.96,
                        precip_mm: 0,
                        precip_in: 0,
                        snow_cm: 0,
                        humidity: 71,
                        cloud: 27,
                        feelslike_c: -1.1,
                        feelslike_f: 30.1,
                        windchill_c: -1.1,
                        windchill_f: 30.1,
                        heatindex_c: 2.5,
                        heatindex_f: 36.4,
                        dewpoint_c: -2.2,
                        dewpoint_f: 28,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 12.3,
                        gust_kph: 19.7,
                        uv: 1,
                        short_rad: 0,
                        diff_rad: 0
                    }
                ]
            }
        ]
    }
}
export default dummyData;